### PR TITLE
A little cleanup feel free to reject :)

### PR DESCRIPTION
**Pull request by Drawaes**
Firstly this is a really cool little project, looking forward to showing it to a few people to expand their mind on how a CPU/OS works. 

I have cleaned up a few things to made it a bit more ".net". I know structure/layout changes can be annoying so feel free to reject if it is not to taste (I also really want to recap your public members that are camel cased but hey). 

Restructure to move code under src node
Move solution to root folder
Remove non generic ProcessCollection

### CODE REVIEW

**Comment by Drawaes** [comment]
I removed any code changes to just have the solution move, I can then submit a second PR after to change the collections, go generic and add mooar var/c#7 stuff. There is a good chance I am hopeless at GIT or it's just being a pain for a big file move like this.

**Comment by shanselman** [comment]
Cool. I also setup AppVeyor for automated builds of PRs https://ci.appveyor.com/project/ScottHanselman/tinyos

**Comment by Drawaes** [comment]
Awesome if you don't mind I might hack away when I have those times when I don't want to waste my life on Facebook etc :) I think it's probably the neatest little way I have seen to explain to people how a cpu and os work for those that missed out on changing to protected mode using assembler :)

**Comment by shanselman** [comment]
Of course. Add an issue when you want to do something so I am not doing the same thing, and try to do little bits at a time so it's not a whole I REWROTE IT OVER AGAIN situation - that's a fork. 

It's a hot mess of code, as you can see, but it's somewhat interesting. I think we need tests (and test-ability) since we could add a bunch of C# 7 isms and we don't REALLY know if it even works correctly now - we just know it doesn't crash ;)

**Pull request merged**
